"""
Builds a full course from a real YouTube playlist: one lesson per video (embedded via a VIDEO
block), with explanatory text/code blocks generated by Groq from that video's own transcript
(never invented from just the title), plus a review quiz at the end of every module.

The course is never attributed to the real creator's identity - see seeder/curator.py's own
docstring for why. Instead:
  - A neutral "curator" account (CURATOR_* in .env) owns the course.
  - A School records where the content actually came from (name/logo/website pulled from the
    real YouTube channel), with an explicit non-affiliation notice - same as the backend's own
    School entity is designed for (pure provenance, never a partnership claim).
  - The very first lesson is an attribution notice crediting the real channel and linking back
    to the original playlist on YouTube.

Usage:
    .venv\\Scripts\\python.exe build_from_playlist.py <playlist_url_or_id>
    .venv\\Scripts\\python.exe build_from_playlist.py  (prompts for the URL interactively)

Options:
    --lessons-per-module N   Videos per module before a review quiz (default 5)
    --max-videos N           Only process the first N videos - useful to try this out cheaply
                              before committing a full run's worth of Groq calls
    --course-name "..."      Override the course name (default: the playlist's own title)
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import uuid

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

from seeder.config import Config, load_config, require_youtube_api_key
from seeder.curator import ensure_curator, ensure_school, grant_school_membership, login_admin
from seeder.http_client import ApiError, HttpClient
from seeder.real_content_generator import generate_lesson_blocks_from_transcript, generate_real_module_quiz
from seeder.swagger import verify_swagger
from seeder.transcript import get_transcript
from seeder.youtube_playlist import PlaylistVideo, fetch_playlist

# A small pause between Groq calls measurably cuts how often the 8000 TPM free-tier rate limit
# (see README.md) gets hit on a run with a couple dozen videos - cheaper than eating the exchange's
# own multi-second retry backoff over and over.
GROQ_CALL_PAUSE_SECONDS = 1.5


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Builds a Coursemaker course from a YouTube playlist.")
    parser.add_argument("playlist", nargs="?", help="Playlist URL or ID. Prompted for if omitted.")
    parser.add_argument("--lessons-per-module", type=int, default=5)
    parser.add_argument("--max-videos", type=int, default=None, help="Only process the first N videos.")
    parser.add_argument("--course-name", default=None, help="Override the course name.")
    parser.add_argument(
        "--exclude", default=None,
        help="Comma-separated YouTube video IDs to skip - playlists often mix in promos/bonus "
             "videos ('Seja apoiador', anniversary specials...) that are not real lessons.",
    )
    return parser.parse_args()


def chunk(items: list, size: int) -> list[list]:
    return [items[i:i + size] for i in range(0, len(items), size)]


def build_attribution_html(channel_title: str, channel_url: str, playlist_url: str) -> str:
    return (
        "<p><strong>Este curso não foi criado pelo Coursemaker.</strong></p>"
        f"<p>Todas as aulas abaixo são vídeos do canal público <strong>{channel_title}</strong>, "
        "incorporados diretamente do YouTube.</p>"
        "<p>O autor original não afiliou este material a esta plataforma - a curadoria e "
        "organização em módulos foi feita por nós apenas para facilitar o estudo. Assista ao "
        f'curso completo e original em <a href="{playlist_url}">{channel_url}</a>.</p>'
    )


def run_playlist_flow(
    playlist_arg: str,
    *,
    lessons_per_module: int = 5,
    max_videos: int | None = None,
    course_name: str | None = None,
    exclude: str | None = None,
) -> None:
    """The reusable core of this script - builds one course from a YouTube playlist.

    Extracted out of `main()` so `main.py`'s interactive menu can call this same flow (with
    defaults) after the user chooses "colar uma playlist", without duplicating any of this logic.
    This script's own CLI (below) still supports every flag for direct/advanced use.
    """
    print("== Coursemaker: curso a partir de playlist real ==")

    config = load_config()
    youtube_api_key = require_youtube_api_key(config)
    verify_swagger(config.api_base_url)

    print(f"[youtube] buscando playlist...")
    playlist = fetch_playlist(youtube_api_key, playlist_arg)
    videos = playlist.videos

    excluded_ids = {v.strip() for v in exclude.split(",") if v.strip()} if exclude else set()
    if excluded_ids:
        before = len(videos)
        videos = [v for v in videos if v.video_id not in excluded_ids]
        print(f"[youtube] {before - len(videos)} video(s) excluido(s) via --exclude")

    if max_videos:
        videos = videos[:max_videos]
    print(f"[youtube] \"{playlist.title}\" (canal: {playlist.channel.title}) - {len(videos)} video(s)")

    http = HttpClient(f"{config.api_base_url}/api/v1")

    print("[auth] preparando conta curadora...")
    curator_token, curator_user = ensure_curator(http, config)
    http.set_token(curator_token)

    print("[auth] preparando escola de origem...")
    admin_token = login_admin(http, config)
    playlist_url = f"https://www.youtube.com/playlist?list={playlist.id}"
    school = ensure_school(
        http, admin_token,
        name=playlist.channel.title,
        description=(
            f"Selo de origem apenas: este material foi curado a partir do canal publico "
            f"\"{playlist.channel.title}\". Nao ha parceria, afiliacao ou endosso oficial entre o "
            "Coursemaker e o canal ou seu criador - os videos permanecem hospedados no YouTube e "
            "sao apenas incorporados aqui."
        ),
        logo_url=playlist.channel.logo_url or None,
        website_url=playlist.channel.url,
    )
    grant_school_membership(http, admin_token, school["id"], curator_user["id"])

    areas = http.get("/areas", auth=False)
    if not areas:
        raise RuntimeError("Nenhuma area cadastrada no backend (GET /areas vazio). Crie uma antes de continuar.")
    area = next((a for a in areas if a["name"] == "Programacao"), areas[0])

    resolved_course_name = (course_name or playlist.title).strip()[:255]
    print(f"[curso] criando \"{resolved_course_name}\"...")
    course = http.post("/courses", {
        "name": resolved_course_name,
        "description": f"Curso baseado na playlist \"{playlist.title}\", do canal {playlist.channel.title}.",
        "landingDescription": (playlist.description or playlist.channel.description or course_name)[:2000],
        "visibility": "public",
        "categories": [],
        "areaId": area["id"],
        "schoolId": school["id"],
    })

    for module in http.get(f"/courses/{course['id']}/modules"):
        http.delete(f"/modules/{module['id']}")

    intro_module = http.post(f"/courses/{course['id']}/modules", {"title": "Antes de começar"})
    intro_lesson = http.post(f"/modules/{intro_module['id']}/lessons", {"title": "Sobre este curso"})
    http.post(f"/lessons/{intro_lesson['id']}/blocks", {
        "type": "text",
        "content": build_attribution_html(playlist.channel.title, playlist.channel.url, playlist_url),
    })

    video_groups = chunk(videos, max(lessons_per_module, 1))
    for group_index, group in enumerate(video_groups, start=1):
        module_title = f"Parte {group_index} de {len(video_groups)}"
        print(f"\n[modulo {group_index}/{len(video_groups)}] \"{module_title}\" ({len(group)} aula(s))")
        module = http.post(f"/courses/{course['id']}/modules", {"title": module_title})

        lessons_for_quiz = []
        for video in group:
            lessons_for_quiz.append(_build_video_lesson(http, config, module["id"], video))
            time.sleep(GROQ_CALL_PAUSE_SECONDS)

        transcribed = [lesson for lesson in lessons_for_quiz if lesson["transcript"]]
        if transcribed:
            _build_module_quiz(http, config, module["id"], module_title, transcribed)
            time.sleep(GROQ_CALL_PAUSE_SECONDS)
        else:
            print("    [quiz] pulado (nenhuma aula deste modulo teve transcricao disponivel)")

    if config.publish_courses:
        http.patch(f"/courses/{course['id']}", {"status": "available"})

    print(f"\nConcluido: /courses/{curator_user.get('nickname', config.curator.nickname)}/{course['slug']}")


def main() -> None:
    """Standalone CLI for this script, with every flag - `main.py`'s menu calls
    `run_playlist_flow` directly instead, with defaults, since it only asks for the URL."""
    args = parse_args()
    playlist_arg = args.playlist or input("URL ou ID da playlist do YouTube: ").strip()
    if not playlist_arg:
        raise SystemExit("Nenhuma playlist informada.")

    run_playlist_flow(
        playlist_arg,
        lessons_per_module=args.lessons_per_module,
        max_videos=args.max_videos,
        course_name=args.course_name,
        exclude=args.exclude,
    )


def _build_video_lesson(http: HttpClient, config: Config, module_id: str, video: PlaylistVideo) -> dict:
    lesson = http.post(f"/modules/{module_id}/lessons", {"title": video.title[:255]})

    http.post(f"/lessons/{lesson['id']}/blocks", {
        "type": "video",
        "content": f"https://www.youtube.com/watch?v={video.video_id}",
    })

    print(f"  [aula] \"{video.title}\" - buscando transcricao...")
    transcript = get_transcript(config, video.video_id)

    if transcript:
        try:
            blocks = generate_lesson_blocks_from_transcript(config, video.title, transcript)
        except Exception as error:  # noqa: BLE001 - one video's content failure should not sink the run
            print(f"    [groq] falhou ao gerar blocos para \"{video.title}\": {error}")
            blocks = []
    else:
        print("    [transcript] indisponivel (legendas desativadas e transcricao por audio falhou)")
        blocks = []

    for block in blocks:
        http.post(f"/lessons/{lesson['id']}/blocks", {
            "type": block["type"],
            "content": block["content"],
            "language": block["language"],
        })

    print(f"    -> {len(blocks)} bloco(s) de conteudo" + ("" if transcript else " (sem transcricao)"))
    return {"title": video.title, "transcript": transcript}


def _build_module_quiz(http: HttpClient, config: Config, module_id: str, module_title: str, lessons: list[dict]) -> None:
    try:
        quiz = generate_real_module_quiz(config, module_title, lessons)
    except Exception as error:  # noqa: BLE001 - a failed quiz should not sink the whole module
        print(f"    [quiz] falhou ao gerar: {error}")
        return

    if quiz is None:
        print("    [quiz] Groq nao retornou uma pergunta valida")
        return

    quiz_lesson = http.post(f"/modules/{module_id}/lessons", {"title": "Revisão do módulo"})
    http.post(f"/lessons/{quiz_lesson['id']}/blocks", {
        "type": "text",
        "content": f"<p><strong>{quiz['prompt']}</strong></p>",
    })

    alternatives = [
        {"id": str(uuid.uuid4()), "text": a["text"], "correct": a["correct"], "explanation": a["explanation"]}
        for a in quiz["alternatives"]
    ]
    http.post(f"/lessons/{quiz_lesson['id']}/blocks", {
        "type": "question",
        "content": json.dumps({"alternatives": alternatives}, ensure_ascii=False),
    })
    print(f"    [quiz] \"{quiz['prompt']}\"")


if __name__ == "__main__":
    try:
        main()
    except ApiError as error:
        print("\nFalha na execucao:", file=sys.stderr)
        print(str(error), file=sys.stderr)
        if error.body:
            print(json.dumps(error.body, indent=2, ensure_ascii=False), file=sys.stderr)
        sys.exit(1)
    except Exception as error:  # noqa: BLE001 - top-level CLI guard
        print("\nFalha na execucao:", file=sys.stderr)
        print(str(error), file=sys.stderr)
        sys.exit(1)
